import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Open_Sans } from "@next/font/google";
import { Noto_Sans_KR } from "@next/font/google";

import BottomNavigation from "@mui/material/BottomNavigation";
import BottomNavigationAction from "@mui/material/BottomNavigationAction";
import RestoreIcon from "@mui/icons-material/Restore";
import FavoriteIcon from "@mui/icons-material/Favorite";
import LocationOnIcon from "@mui/icons-material/LocationOn";

const enFont = Open_Sans({ subsets: ["latin"] });
const krFont = Noto_Sans_KR({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export default function Home() {
  const [value, setValue] = useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <BottomNavigation
          showLabels
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
          <BottomNavigationAction label="Recents" icon={<RestoreIcon />} />
          <BottomNavigationAction label="Favorites" icon={<FavoriteIcon />} />
          <BottomNavigationAction label="Nearby" icon={<LocationOnIcon />} />
        </BottomNavigation>
        ;
        <div className="">
          <p>
            Get started by editing&nbsp;
            <code className="">src/pages/index.tsx</code>
          </p>
          <div></div>
        </div>
        <div className="">
          <h2 className={enFont.className}>
            Docs <span>-&gt;</span>
          </h2>
          <p className={enFont.className}>
            Find in-depth information about Next.js features and&nbsp;API.
          </p>

          <h2 className={enFont.className}>
            Learn <span>-&gt;</span>
          </h2>
          <p className={enFont.className}>
            Learn about Next.js in an interactive course with&nbsp;quizzes!
          </p>

          <h2 className={enFont.className}>
            Templates <span>-&gt;</span>
          </h2>
          <p className={enFont.className}>
            Discover and deploy boilerplate example Next.js&nbsp;projects.
          </p>

          <h2 className={krFont.className}>
            배포 <span>-&gt;</span>
          </h2>
          <p className={enFont.className}>
            Instantly deploy your Next.js site to a shareable URL
            with&nbsp;Vercel.
          </p>
        </div>
      </main>
    </>
  );
}
